server:
  port: 8888
  servlet:
    context-path: /api
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ledger?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      # MySql、PostgreSQL校验
      validation-query: select 1
      # Oracle校验
      #validation-query: select 1 from dual
      validation-query-timeout: 2000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: 123!654
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
        session-stat-enable: true
        session-stat-max-count: 10
  redis:
    host: localhost
    database: 0
    port: 6379
  application:
    name: ledger
mybatis-plus:
    mapper-locations: classpath*:/mapper/**Mapper.xml
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
ledger:
  jwt:
    expire: 604800 #7天，秒单位
    secret: ledgerisasimplerecordmoneyprogremandwillbebetter
    header: Authorization
  smms:
    username: xxxxx
    password: xxxxx
  webdav:
    url: https://yiandrive.com/dav
    client: xxxxxxx
    secret: xxxxxxx
    root-path: ledger

